/**
 * routes/intelligence.js
 *
 * Intelligence and learning engine routes.
 * Data comes from Redis (cache) and the DB (comments, metrics).
 *
 * Routes:
 *   GET  /intelligence/summary      — AI-readable performance summary (from Redis)
 *   GET  /intelligence/research     — niche/trend research (from Redis)
 *   POST /intelligence/refresh             — queue a research refresh (returns jobId immediately)
 *   GET  /intelligence/refresh/status/:id  — poll job status (pending/completed/failed)
 *   GET  /intelligence/comments     — recent comments with sentiment analysis
 *   GET  /intelligence/performance  — aggregated post performance metrics
 *   GET  /intelligence/preflight    — blended pre-flight panel data for the brief form
 *
 * The summary and research keys in Redis are read by llmService.js at
 * generation time, so better data = better posts.
 *
 * All queries are scoped to req.user.id via enforceTenancy.
 */

const express = require('express');
const router  = express.Router();

const { requireAuth }        = require('../middleware/auth');
const { enforceTenancy }     = require('../middleware/tenancy');
const { standardLimiter }    = require('../middleware/rateLimit');
const { checkLimit }         = require('../middleware/checkLimit');
const { cacheGet }           = require('../services/redisService');
const { refreshResearch }    = require('../agents/researchAgent');
const { researchQueue }      = require('../queues');
const { getCohortBenchmark } = require('../agents/performanceAgent');
const { predictEngagement }  = require('../services/performancePredictorService');
const { minePainPoints }     = require('../services/painPointMinerService');
const { getVoiceProfile }    = require('../services/brandVoiceService');

// Apply auth + tenancy + intelligence tier check to all routes in this file
router.use(requireAuth, enforceTenancy, checkLimit('intelligence_dashboard'));

// ----------------------------------------------------------------
// GET /intelligence/summary
// Returns the cached performance intelligence summary for this user.
// This is the same text that gets injected into LLM prompts.
// Generated by performanceAgent after each metrics polling cycle.
// ----------------------------------------------------------------
router.get('/summary', standardLimiter, async (req, res) => {
  try {
    const summary = await cacheGet(`intelligence:${req.user.id}`);

    return res.json({
      summary: summary || null,
      message: summary
        ? 'Intelligence summary loaded from cache'
        : 'No intelligence data yet. Publish posts and let the performance agent run to build your intelligence profile.'
    });

  } catch (err) {
    console.error('[Intelligence] Summary fetch error:', err.message);
    return res.status(500).json({ error: 'Failed to fetch intelligence summary' });
  }
});

// ----------------------------------------------------------------
// GET /intelligence/research
// Returns cached niche/trend research for this user.
// Generated by researchAgent — refreshed weekly or on manual trigger.
// ----------------------------------------------------------------
router.get('/research', standardLimiter, async (req, res) => {
  try {
    const research = await cacheGet(`research:${req.user.id}`);

    return res.json({
      research: research || null,
      message: research
        ? 'Research loaded from cache'
        : 'No research data yet. Use POST /intelligence/refresh to generate your first research brief.'
    });

  } catch (err) {
    console.error('[Intelligence] Research fetch error:', err.message);
    return res.status(500).json({ error: 'Failed to fetch research data' });
  }
});

// ----------------------------------------------------------------
// POST /intelligence/refresh
// Queues a research refresh job for the current user and returns
// immediately with a jobId. The frontend polls /refresh/status/:jobId
// until the job completes, then re-fetches /intelligence/research.
//
// Previously this called refreshResearch() inline and the HTTP
// request sat open for 10-20 seconds waiting for Groq. Async queue
// returns in <50ms regardless of LLM speed.
// ----------------------------------------------------------------
router.post('/refresh', standardLimiter, async (req, res) => {
  try {
    const job = await researchQueue.add(
      'research-user',
      { userId: req.user.id },
      {
        // Unique jobId per request — allows multiple manual refreshes
        // without colliding with the weekly scheduled job
        jobId: `research-manual-${req.user.id}-${Date.now()}`,
        removeOnComplete: { count: 50 },
        removeOnFail:     { count: 20 }
      }
    );

    return res.json({ status: 'queued', jobId: job.id });

  } catch (err) {
    console.error('[Intelligence] Research refresh queue error:', err.message);
    return res.status(500).json({ error: err.message || 'Failed to queue research refresh' });
  }
});

// ----------------------------------------------------------------
// GET /intelligence/refresh/status/:jobId
// Polls the status of a queued research job.
// Returns: { status: 'pending' | 'completed' | 'failed', error? }
// Once 'completed', the frontend re-fetches /intelligence/research.
// ----------------------------------------------------------------
router.get('/refresh/status/:jobId', standardLimiter, async (req, res) => {
  try {
    const job = await researchQueue.getJob(req.params.jobId);

    if (!job) {
      return res.status(404).json({ error: 'Job not found.' });
    }

    const state = await job.getState();

    if (state === 'completed') {
      return res.json({ status: 'completed' });
    }

    if (state === 'failed') {
      return res.json({ status: 'failed', error: job.failedReason || 'Research generation failed.' });
    }

    // waiting / active / delayed — all 'pending' from the user's perspective
    return res.json({ status: 'pending' });

  } catch (err) {
    console.error('[Intelligence] Research status poll error:', err.message);
    return res.status(500).json({ error: 'Failed to check job status.' });
  }
});

// ----------------------------------------------------------------
// GET /intelligence/comments
// Returns recent ingested comments with sentiment labels.
// Optional: ?sentiment=positive|neutral|negative  ?limit=50
// ----------------------------------------------------------------
router.get('/comments', standardLimiter, async (req, res) => {
  const limit = Math.min(parseInt(req.query.limit) || 50, 200);

  try {
    let query = req.db
      .from('comments')
      .select('id, platform, comment_text, author_handle, sentiment, trigger_matched, dm_sent, ingested_at, posts(hook, platform)')
      .order('ingested_at', { ascending: false })
      .limit(limit);

    if (req.query.sentiment) {
      query = query.eq('sentiment', req.query.sentiment);
    }

    const { data, error } = await query;
    if (error) throw new Error(error.message);

    // Aggregate sentiment counts for the summary bar
    const sentimentCounts = { positive: 0, neutral: 0, negative: 0 };
    (data || []).forEach(c => {
      if (sentimentCounts[c.sentiment] !== undefined) sentimentCounts[c.sentiment]++;
    });

    return res.json({
      comments:       data || [],
      sentimentCounts
    });

  } catch (err) {
    console.error('[Intelligence] Comments fetch error:', err.message);
    return res.status(500).json({ error: 'Failed to fetch comments' });
  }
});

// ----------------------------------------------------------------
// GET /intelligence/performance
// Returns aggregated post performance metrics grouped by platform.
// Optional: ?days=30 (default 30, max 90)
// ----------------------------------------------------------------
router.get('/performance', standardLimiter, async (req, res) => {
  const days   = Math.min(parseInt(req.query.days) || 30, 90);
  const cutoff = new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();

  try {
    // Get the most recent metric snapshot per post (take latest recorded_at)
    const { data: metrics, error } = await req.db
      .from('post_metrics')
      .select('platform, likes, comments, shares, saves, reach, impressions, video_views, recorded_at')
      .gte('recorded_at', cutoff)
      .order('recorded_at', { ascending: false })
      .limit(5000);

    if (error) throw new Error(error.message);

    const rows = metrics || [];

    // Aggregate by platform
    const byPlatform = {};
    rows.forEach(m => {
      if (!byPlatform[m.platform]) {
        byPlatform[m.platform] = { posts:0, likes:0, comments:0, shares:0, saves:0, reach:0, impressions:0, video_views:0 };
      }
      const p = byPlatform[m.platform];
      p.posts++;
      p.likes       += (m.likes       || 0);
      p.comments    += (m.comments    || 0);
      p.shares      += (m.shares      || 0);
      p.saves       += (m.saves       || 0);
      p.reach       += (m.reach       || 0);
      p.impressions += (m.impressions || 0);
      p.video_views += (m.video_views || 0);
    });

    // Build summary rows with averages
    const summary = Object.entries(byPlatform).map(([platform, totals]) => ({
      platform,
      total_posts:      totals.posts,
      total_likes:      totals.likes,
      total_comments:   totals.comments,
      total_shares:     totals.shares,
      total_reach:      totals.reach,
      total_impressions: totals.impressions,
      avg_likes:        Math.round(totals.likes / totals.posts),
      avg_reach:        Math.round(totals.reach / totals.posts)
    }));

    // Overall totals
    const totals = {
      total_posts:      rows.length,
      total_likes:      rows.reduce((s, m) => s + (m.likes || 0), 0),
      total_comments:   rows.reduce((s, m) => s + (m.comments || 0), 0),
      total_reach:      rows.reduce((s, m) => s + (m.reach || 0), 0),
      total_impressions: rows.reduce((s, m) => s + (m.impressions || 0), 0)
    };

    return res.json({ summary, totals, days });

  } catch (err) {
    console.error('[Intelligence] Performance fetch error:', err.message);
    return res.status(500).json({ error: 'Failed to fetch performance data' });
  }
});

// ----------------------------------------------------------------
// GET /intelligence/preflight
//
// Returns blended pre-generation insights for the brief pre-flight
// panel. Combines three signal sources:
//
//   1. User's own intelligence (Redis: intelligence:{userId})
//      — their own top hooks, best platform, best post time
//
//   2. Cohort benchmark (cohort_performance table)
//      — averages from peers with same industry + geo + platform
//      — falls back to progressively broader cohorts if needed
//
//   3. Research cache (Redis: research:{userId})
//      — trending topics and niche insights from the research agent
//
// Query params:
//   platform  — required. e.g. 'instagram'
//   post_type — optional. e.g. 'promotional'
//
// Response shape:
//   {
//     own_intelligence: string | null,     // user's own perf summary
//     cohort: { ... } | null,              // cohort benchmark row
//     research: string | null,             // trend research text
//     signals: {                           // blended recommendations
//       best_post_hours: int[],
//       top_tones: string[],
//       top_hooks: string[],
//       cohort_avg_likes: number,
//       cohort_sample_size: number
//     } | null
//   }
// ----------------------------------------------------------------
router.get('/preflight', standardLimiter, async (req, res) => {
  const { platform, post_type } = req.query;

  if (!platform) {
    return res.status(400).json({ error: 'platform query param is required' });
  }

  try {
    // Fetch all three signal sources in parallel
    const [ownIntelligence, cohortRow, research] = await Promise.all([
      cacheGet(`intelligence:${req.user.id}`),
      getCohortBenchmark(req.user.id, platform, post_type || null),
      cacheGet(`research:${req.user.id}`)
    ]);

    // Blend cohort signals into a structured recommendations object.
    // If no cohort data exists yet, signals is null — the frontend
    // shows a "build your history" message rather than empty data.
    let signals = null;

    if (cohortRow) {
      signals = {
        // Cohort-level benchmarks
        cohort_avg_likes:    cohortRow.avg_likes,
        cohort_avg_reach:    cohortRow.avg_reach,
        cohort_avg_comments: cohortRow.avg_comments,
        cohort_sample_size:  cohortRow.sample_size,
        cohort_platform:     cohortRow.platform,
        cohort_post_type:    cohortRow.post_type || 'all post types',

        // Behavioural patterns from the cohort
        best_post_hours: cohortRow.best_post_hours || [],
        top_tones:       cohortRow.top_tones       || [],
        top_hooks:       cohortRow.top_hooks        || []
      };
    }

    return res.json({
      own_intelligence: ownIntelligence  || null,
      research:         research         || null,
      cohort:           cohortRow        || null,
      signals
    });

  } catch (err) {
    console.error('[Intelligence] Preflight error:', err.message);
    return res.status(500).json({ error: 'Failed to load preflight data' });
  }
});

// ----------------------------------------------------------------
// POST /intelligence/predict
//
// Predicts engagement performance for a post draft BEFORE publishing.
// Uses cohort benchmarks + user's own history to estimate likes,
// comments, and reach — plus factors explaining the score.
//
// Body: { platform, post_type, tone, hook, caption }
// ----------------------------------------------------------------
router.post('/predict', standardLimiter, checkLimit('performance_predictor'), async (req, res) => {
  const { platform, post_type, tone, hook, caption } = req.body;

  if (!platform) {
    return res.status(400).json({ error: 'platform is required' });
  }

  try {
    const prediction = await predictEngagement(req.user.id, {
      platform,
      post_type: post_type || null,
      tone:      tone      || null,
      hook:      hook       || '',
      caption:   caption    || ''
    });

    return res.json({ prediction });

  } catch (err) {
    console.error('[Intelligence] Prediction error:', err.message);
    return res.status(500).json({ error: 'Failed to generate prediction' });
  }
});

// ----------------------------------------------------------------
// GET /intelligence/pain-points
//
// Mines audience comments from the last 30 days to extract recurring
// pain points, questions, and desires. Groups them into themes with
// frequency counts and example quotes.
//
// Optional: ?platform=instagram  ?limit=5
// ----------------------------------------------------------------
router.get('/pain-points', standardLimiter, checkLimit('pain_point_miner'), async (req, res) => {
  try {
    const painPoints = await minePainPoints(req.user.id, {
      platform: req.query.platform || null,
      limit:    parseInt(req.query.limit) || 5
    });

    return res.json(painPoints);

  } catch (err) {
    console.error('[Intelligence] Pain-point mining error:', err.message);
    return res.status(500).json({ error: 'Failed to mine pain points' });
  }
});

// ----------------------------------------------------------------
// GET /intelligence/voice-profile
//
// Returns the user's learned brand voice profile — built from
// analyzing their published posts over time. Includes writing
// patterns, vocabulary preferences, sentence structure, and tone.
// ----------------------------------------------------------------
router.get('/voice-profile', standardLimiter, checkLimit('brand_voice_tracker'), async (req, res) => {
  try {
    const profile = await getVoiceProfile(req.user.id);

    return res.json({ voice_profile: profile });

  } catch (err) {
    console.error('[Intelligence] Voice profile error:', err.message);
    return res.status(500).json({ error: 'Failed to fetch voice profile' });
  }
});

module.exports = router;
